### get all
GET http://localhost:3000/contacts

### getById

GET http://localhost:3000/contacts/61438692d3598c8e40b94fc5

### post new

POST http://localhost:3000/contacts
Content-Type: application/json

{
    "firstName": "Hank",
    "lastName": "Beck",
    "email": "aaronmicalbeck@gmail.com",
    "message": "posting from route.rest file"
}

### deleteById

DELETE http://localhost:3000/contacts/61438692d3598c8e40b94fc5

### updateById

PATCH http://localhost:3000/contacts/6143871f803d22fcfbeae97e
Content-Type: application/json

{
    "firstName": "Arto"
}

